// Code generated by go run ./cmd/reset; DO NOT EDIT.

package pool

func (rs *TestStruct) Reset() {
	if rs == nil {
		return
	}

	rs.Value = 0
	rs.Name = ""
	rs.Tags = rs.Tags[:0]
	clear(rs.Settings)
	if rs.Nested != nil {
		if resetter, ok := any(rs.Nested).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
