// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/user.go -destination=internal/service/mock/mock_user.go -package=mock
//

// Package mock_user is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/PolRuff/urlshort/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUserService) CountUsers(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserServiceMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserService)(nil).CountUsers), ctx)
}

// DeleteUserUrls mocks base method.
func (m *MockUserService) DeleteUserUrls(ctx context.Context, userID uint32, shortIDs []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteUserUrls", ctx, userID, shortIDs)
}

// DeleteUserUrls indicates an expected call of DeleteUserUrls.
func (mr *MockUserServiceMockRecorder) DeleteUserUrls(ctx, userID, shortIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserUrls", reflect.TypeOf((*MockUserService)(nil).DeleteUserUrls), ctx, userID, shortIDs)
}

// GetUserUrls mocks base method.
func (m *MockUserService) GetUserUrls(ctx context.Context, userID uint32) ([]model.UserUrls, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUrls", ctx, userID)
	ret0, _ := ret[0].([]model.UserUrls)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserUrls indicates an expected call of GetUserUrls.
func (mr *MockUserServiceMockRecorder) GetUserUrls(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUrls", reflect.TypeOf((*MockUserService)(nil).GetUserUrls), ctx, userID)
}
