// Package reset is a code generator that creates Reset() methods for structs
// annotated with "// generate:reset".
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// FieldInfo holds information about a struct field for code generation.
// generate:reset
type FieldInfo struct {
	Name      string
	TypeStr   string
	IsPointer bool
	IsStruct  bool
	IsSlice   bool
	IsMap     bool
}

// StructInfo holds information about a struct that needs a Reset method.
// generate:reset
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

// PackageInfo holds all structs to be processed in a single package.
// generate:reset
type PackageInfo struct {
	PackageName string
	Structs     []StructInfo
}

const resetTemplate = `// Code generated by go run ./cmd/reset; DO NOT EDIT.

package {{.PackageName}}

{{range .Structs}}
func (rs *{{.Name}}) Reset() {
	if rs == nil {
		return
	}
	{{range .Fields}}
	{{- if .IsPointer}}
	if rs.{{.Name}} != nil {
		{{- if .IsStruct}}
		if resetter, ok := any(rs.{{.Name}}).(interface{ Reset() }); ok {
			resetter.Reset()
		}
		{{- else if .IsSlice}}
		*rs.{{.Name}} = (*rs.{{.Name}})[:0]
		{{- else if .IsMap}}
		clear(*rs.{{.Name}})
		{{- else}}
		*rs.{{.Name}} = {{zeroValue .TypeStr}}
		{{- end}}
	}
	{{- else}}
	{{- if .IsStruct}}
	if resetter, ok := any(rs.{{.Name}}).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	{{- else if .IsSlice}}
	rs.{{.Name}} = rs.{{.Name}}[:0]
	{{- else if .IsMap}}
	clear(rs.{{.Name}})
	{{- else}}
	rs.{{.Name}} = {{zeroValue .TypeStr}}
	{{- end}}
	{{- end}}
	{{- end}}
}
{{end}}
`

var tmpl *template.Template

func init() {
	funcMap := template.FuncMap{
		"zeroValue": func(typeStr string) string {
			switch typeStr {
			case "string":
				return `""`
			case "bool":
				return `false`
			case "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"float32", "float64", "complex64", "complex128":
				return "0"
			default:
				return "{}" // For named types or other zero values
			}
		},
	}
	tmpl = template.Must(template.New("reset").Funcs(funcMap).Parse(resetTemplate))
}

func main() {
	currentDir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to get current directory: %v\n", err)
		os.Exit(1)
	}

	var dir string
	flag.StringVar(&dir, "dir", currentDir, "Directory to scan for Go packages")
	flag.Parse()

	err = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}

		// Skip directories mock
		if info.Name() == "mock" {
			return filepath.SkipDir
		}

		pkgInfo, err := processPackage(path)
		if err != nil {
			return err
		}

		if len(pkgInfo.Structs) > 0 {
			if err := writeResetFile(path, pkgInfo); err != nil {
				return fmt.Errorf("failed to write reset file for package %s: %w", path, err)
			}
		}

		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func processPackage(pkgDir string) (*PackageInfo, error) {
	// Read all .go files in the directory
	entries, err := os.ReadDir(pkgDir)
	if err != nil {
		return nil, err
	}

	var goFiles []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
			goFiles = append(goFiles, filepath.Join(pkgDir, entry.Name()))
		}
	}

	if len(goFiles) == 0 {
		return &PackageInfo{}, nil
	}

	fset := token.NewFileSet()
	var pkgName string
	var structs []StructInfo

	// Parse each file individually
	for _, filePath := range goFiles {
		file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}

		// Get package name from the first file
		if pkgName == "" {
			pkgName = file.Name.Name
		}

		// Skip main package
		if pkgName == "main" {
			return &PackageInfo{}, nil
		}

		// Process declarations in this file
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				hasResetComment := false
				if genDecl.Doc != nil {
					for _, comment := range genDecl.Doc.List {
						if strings.Contains(comment.Text, "// generate:reset") {
							hasResetComment = true
							break
						}
					}
				}

				if hasResetComment {
					fields := extractFields(structType.Fields)
					structs = append(structs, StructInfo{
						Name:   typeSpec.Name.Name,
						Fields: fields,
					})
				}
			}
		}
	}

	return &PackageInfo{
		PackageName: pkgName,
		Structs:     structs,
	}, nil
}

// extractFields processes struct fields and extracts their type information.
func extractFields(fieldList *ast.FieldList) []FieldInfo {
	if fieldList == nil {
		return nil
	}

	var fields []FieldInfo
	for _, field := range fieldList.List {
		if len(field.Names) == 0 {
			continue // Embedded field
		}

		fieldName := field.Names[0].Name
		fieldType := field.Type

		info := FieldInfo{
			Name: fieldName,
		}

		// Handle pointer types
		if starExpr, ok := fieldType.(*ast.StarExpr); ok {
			info.IsPointer = true
			fieldType = starExpr.X
		}

		// Determine the base type
		switch t := fieldType.(type) {
		case *ast.Ident:
			info.TypeStr = t.Name
			info.IsStruct = !isBasicType(t.Name)
		case *ast.SelectorExpr:
			info.TypeStr = fmt.Sprintf("%s.%s", t.X, t.Sel)
			info.IsStruct = true
		case *ast.ArrayType:
			if t.Len == nil {
				info.IsSlice = true
			}
			info.TypeStr = "[]..."
		case *ast.MapType:
			info.IsMap = true
			info.TypeStr = "map[...]"
		case *ast.StructType:
			info.IsStruct = true
			info.TypeStr = "struct{}"
		default:
			info.TypeStr = "unknown"
			info.IsStruct = false
		}

		fields = append(fields, info)
	}

	return fields
}

// isBasicType checks if a type name is a Go basic type.
func isBasicType(name string) bool {
	basicTypes := map[string]bool{
		"bool":       true,
		"string":     true,
		"int":        true,
		"int8":       true,
		"int16":      true,
		"int32":      true,
		"int64":      true,
		"uint":       true,
		"uint8":      true,
		"uint16":     true,
		"uint32":     true,
		"uint64":     true,
		"uintptr":    true,
		"float32":    true,
		"float64":    true,
		"complex64":  true,
		"complex128": true,
		"byte":       true,
		"rune":       true,
	}
	return basicTypes[name]
}

// writeResetFile generates and writes the reset.gen.go file.
func writeResetFile(pkgDir string, pkgInfo *PackageInfo) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, pkgInfo); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write the raw buffer for debugging
		formatted = buf.Bytes()
	}

	outputPath := filepath.Join(pkgDir, "reset.gen.go")
	return os.WriteFile(outputPath, formatted, 0644)
}
